name: "Build, Lint & Test"

on:
  push:
    branches: [main, production]
  pull_request:
    branches: [main, production]

jobs:
  build:
    if: ${{!github.event.pull_request.head.repo.fork}}
    name: "Install Dependencies"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/cache-dependencies
      - uses: ./.github/actions/cache-build

  lint:
    if: ${{!github.event.pull_request.head.repo.fork}}
    name: "Lint"
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/cache-dependencies
      - uses: ./.github/actions/cache-build
      - name: "Run Linting Checks"
        shell: bash
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: pnpm lint

  test:
    if: ${{!github.event.pull_request.head.repo.fork}}
    name: Unit & Integration Tests
    needs: [build]
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/cache-dependencies
      - uses: ./.github/actions/cache-build
      - name: Run Unit and Integration Tests
        run: pnpm test:coverage
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-coverage
          path: |
            coverage/

  playwright:
    if: ${{!github.event.pull_request.head.repo.fork}}
    name: E2E Tests
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/cache-dependencies
      - uses: ./.github/actions/cache-build
      - name: Install Playwright Browsers
        run: pnpm dlx playwright install chromium
      - name: Run tests
        run: xvfb-run pnpm test:e2e
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: e2e-tests-results
          path: |
            apps/**/playwright-report/
